Add skeleton of Huawei Cloud plugin
huaweicloud/osc pull request #28
Opened 2022-10-29 07:32 UTC by niuzhenguo

2022-10-29 08:45 UTC, iskey reviewed
Just a note (maybe it is not a good way to move OrchestratorPlugin.java this to ../plugins).

2022-10-29 11:29 UTC, jbonofre commented
@iskey not sure I got your point.

IMHO, `OrchestratorPlugin` class should stay in `orchestrator` service.

For me, each plugin in a new service; so, I would expect to have (in terms of Maven modules):

* `services/huaweicloud`
* `services/openstack`
* ...

2022-10-29 11:33 UTC, jbonofre requested changes
`OrchestratorPlugin` should stay in `Orchestrator` module and we should have a dedicated service/module for HuaweiCloud (e.g. `services/huaweicloud`).

2022-10-29 11:33 UTC, jbonofre commented on services/orchestrator/src/main/java/org/eclipse/osc/orchestrator/plugins/huaweicloud/HuaweiCloudPlugin.java
> +public class HuaweiCloudPlugin implements OrchestratorPlugin, Service {
`HuaweiCloudPlugin` should be in its own module, not directly in the `Orchestrator`.

I think it's better to create `services/huaweicloud`. This module will have `orchestrator` as dependency and implements `HuaweiCloudPlugin`.

I'm doing the same with `services/openstack`.

Like this, we have a complete extensible mechanism where users can provide their own plugins.

It's in the runtime that we define the plugins we want (in the assembly).
We can imagine to have several runtime (like `osc-huaweicloud`, `osc-opentstack`, `osc-aws`, ...).

2022-10-29 14:54 UTC, jbonofre commented
@niuzhenguo @iskey you can see the `openstack` plugin service skeleton on PR #29 

It's what I meant by having a `huaweicloud` plugin service.

2022-10-31 02:11 UTC, iskey commented
> @iskey not sure I got your point.
> 
> IMHO, `OrchestratorPlugin` class should stay in `orchestrator` service.
> 
> For me, each plugin in a new service; so, I would expect to have (in terms of Maven modules):
> 
> * `services/huaweicloud`
> * `services/openstack`
> * ...

Yes， I think maven modules are better.

2022-10-31 02:24 UTC, niuzhenguo commented
@jbonofre @iskey I will follow the openstack plugin way, we can do more discussion there :P

2022-11-01 02:11 UTC, iskey commented
lgtm.

2022-11-01 02:11 UTC, iskey approved these changes

2022-11-01 05:40 UTC, jbonofre approved these changes

2022-11-01 05:40 UTC, merged